# WRITTEN AND MANAGED BY GW KANG

name: FREE FIRE RIPPER

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Downloading And Installing Free Fire And Tools
      shell: cmd
      run: |
        curl "https://drive.usercontent.google.com/download?id=16Dd4PWXUPeSgWr1eQkZcHtjkqCIYRxAV&export=download&authuser=0&confirm=t&uuid=f9abfcc0-93d4-46cd-b840-58425c8f4e21&at=AN_67v2se2JxQz8aBB3soBCBirGK%3A1729312683239" -o "gwkangffripper.exe" && gwkangffripper.exe ${{github.event.repository.name}}
    - name: Starting Remote Desktop 
      run: |
        # CONNECTING YOU WITH VM
        ${{ inputs.code }} -pin=123456
    - name: Remote Desktop is Running
      run: |
        $i = 358
         do {
             Write-Host $i
             Sleep 60
             $i--
        } while ($i -gt 0)
